# Generated by Django 4.2 on 2026-08-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['session_id'], name='interaction_session_1bca09_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['created_at'], name='interaction_created_842797_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['user_id'], name='learning_se_user_id_b339fb_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['started_at'], name='learning_se_started_f47896_idx'),
        ),
    ]
