# Generated by Django 4.2 on 2026-08-29 07:03

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('word', models.CharField(max_length=255)),
                ('translation', models.CharField(blank=True, max_length=255, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval', models.IntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('repetitions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vocabulary Card',
                'verbose_name_plural': 'Vocabulary Cards',
                'db_table': 'vocabulary_cards',
            },
        ),
        migrations.AddIndex(
            model_name='vocabularycard',
            index=models.Index(fields=['user_id', 'next_review'], name='vocabulary__user_id_ebd686_idx'),
        ),
    ]
