# Generated by Django 4.2 on 2026-08-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_vocabularycard_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vocabularycard',
            name='vocabulary__user_id_ebd686_idx',
        ),
        migrations.AddField(
            model_name='vocabularycard',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddIndex(
            model_name='vocabularycard',
            index=models.Index(fields=['user_id', 'language', 'next_review'], name='vocabulary__user_id_59563d_idx'),
        ),
    ]
