# Generated by Django 4.2 on 2026-08-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_vocabularycard_vocabulary__user_id_ebd686_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'Learner / User'), ('admin', 'Admin')], default='user', max_length=50),
        ),
    ]
