# Generated by Django 4.2 on 2026-09-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_turn_limit',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_turns_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_turn_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
