# Generated by Django 4.2 on 2026-09-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_daily_turn_limit_user_daily_turns_used_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['session_id', 'created_at'], name='log_sess_created_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['user_id', '-started_at'], name='sess_user_started_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='user_username_idx'),
        ),
    ]
