from django.urls import path
from . import views

urlpatterns = [
    path("", views.home_view, name="home"),
    path("app/", views.spa_web_view, name="spa_web"),
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("api/auth/register/", views.register_view, name="api_register"),
    path("api/auth/login/", views.login_view, name="api_login"),
    path("api/auth/logout/", views.logout_view, name="api_logout"),
    path("api/auth/me/", views.api_me, name="api_me"),
    path("api/auth/oauth-sync/", views.OAuthSessionSyncView.as_view(), name="api_oauth_sync"),
    path("api/scenarios/", views.scenarios_list, name="scenarios_list"),
    path("api/scenarios/<int:scenario_id>/", views.ScenarioDetailView.as_view(), name="scenario_detail"),
    path("api/sessions/start/", views.StartSessionView.as_view(), name="start_session"),
    path("api/debug-session/", views.DebugSessionView.as_view(), name="debug_session"),
    path("api/sessions/<uuid:session_id>/respond/", views.SubmitResponseView.as_view(), name="submit_response"),
    path("api/sessions/<uuid:session_id>/respond-audio/", views.SubmitAudioResponseView.as_view(), name="submit_audio_response"),
    path("api/dashboard/<uuid:user_id>/", views.DashboardView.as_view(), name="user_dashboard"),
    path("api/sessions/history/<uuid:user_id>/", views.SessionHistoryView.as_view(), name="session_history"),
    path("api/user/profile/", views.UserProfileUpdateView.as_view(), name="user_profile_update_self"),
    path("api/user/<uuid:user_id>/profile/", views.UserProfileUpdateView.as_view(), name="user_profile_update"),
    path("api/user/<uuid:user_id>/analytics/", views.UserAnalyticsView.as_view(), name="user_analytics"),
    path("api/auth/upgrade/", views.UpgradeToProView.as_view(), name="api_upgrade_pro"),
    path("api/sessions/<uuid:session_id>/logs/", views.SessionLogsView.as_view(), name="session_logs"),
    path("api/flashcards/due/", views.FlashcardDueView.as_view(), name="api_flashcards_due"),
    path("api/flashcards/<uuid:card_id>/review/", views.FlashcardReviewView.as_view(), name="api_flashcards_review"),
]